# Generated by Django 5.0.1 on 2024-04-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='img',
            field=models.ImageField(default='fnj', upload_to='images'),
            preserve_default=False,
        ),
    ]
