# Generated by Django 5.0.1 on 2024-04-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0003_teammember_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='img',
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default='jjk', upload_to='team_images/'),
            preserve_default=False,
        ),
    ]
