# Generated by Django 5.0.1 on 2024-04-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0004_rename_desc_teammember_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team_images'),
        ),
    ]
