# Generated by Django 5.0.1 on 2024-04-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0006_rename_description_teammember_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
